// Adjust the import based on your file structure
'use client';
import Head from 'next/head';
import Navbar from '../Component/Navbar';
import { Pending } from '../Component/Pending';
import { Comments } from '../Component/Comments';
import { FaArrowRight } from 'react-icons/fa';
import { Approvals } from '../Component/Approvals';
import Funds from '../Component/Funds';
import { token } from '../context/context';
import { useState, useContext, useEffect } from 'react';

export default function Home() {
    const [email, setEmail] = useState('arpitraj@gmail.com');

    return (
        <>
            <token.Provider value={email}>
                <div className="bg-gray-150 w-full min-h-screen">
                    <Head>
                        <title>Home Page</title>
                        <meta name="description" content="Generated by create next app" />
                        <link rel="icon" href="/favicon.ico" />
                    </Head>
                    <Navbar />
                    <div className="flex items-center ml-3 my-4">
                        <span className="mr-2">
                            <FaArrowRight />
                        </span>
                        <span className="text-3xl font-semibold text-blue-900 hover:font-black cursor-pointer">
                            PENDING
                        </span>
                    </div>
                    <div className="flex flex-col lg:flex-row">
                        <div className="w-full lg:w-[70% p-4">
                            <Pending />
                        </div>
                        <div className="w-full lg:w-[30%] flex flex-col -mt-3">
                            <div className="w-full lg:h-[20vh] p-4">
                                <Comments />
                            </div>
                            <div className="w-full p-4">
                                <Approvals />
                            </div>
                            <div className="w-full p-4 lg:-auto mt-0">
                                <Funds />
                            </div>
                        </div>
                    </div>
                </div>
            </token.Provider>
        </>
    );
}
