POST http://localhost:3000/newUser
Content-Type: application/json

{
    "userName": "Arpit Raj",
    "email": "arpitraj@gmail.com",
    "password": "123456"
}

###

POST http://localhost:3000/test-cookie
credentials: 'include'
Content-Type: application/json
